name: flutter_chat_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.9.1
  cupertino_icons: ^1.0.2
  emoji_picker_flutter: ^1.6.1
  file_picker: ^5.5.0
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.6
  firebase_ui_auth: 
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.6.9
  get: 
  get_thumbnail_video: ^0.6.1
  google_fonts: ^5.1.0
  intl: 
  path: ^1.8.3
  appinio_video_player: ^1.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true
  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
